version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    container_name: newswebcont
    expose:
      - '3000'
    ports:
      - "8000:3000"
    command: npm start
    